application: bamboo-velocity-87603
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest

- name: numpy
  version: latest

- name: MySQLdb
  version: "latest"

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: fanduelweb.app